PREFIX base:        <http://example.com/tutorial3/vocabulary/base#>
PREFIX mission:     <http://example.com/tutorial3/vocabulary/mission#>

SELECT DISTINCT ?i
WHERE {
	<http://example.com/tutorial3/description/una1#C2> mission:presents ?i .
}
ORDER BY ?i
