PREFIX mission: <http://example.com/tutorial/vocabulary/mission#>

SELECT ?g ?c ?i ?cid ?iid
WHERE {
    GRAPH ?g {
        ?c
            mission:presents ?i ;
            mission:hasIdentifier ?cid .
        ?i mission:hasIdentifier ?iid .
    }
}
ORDER BY ?g ?c ?i