PREFIX mission:     <http://example.com/tutorial/vocabulary/mission#>

SELECT ?c ?i ?cid ?iid
WHERE {
	?c
		mission:presents ?i ;
		mission:hasIdentifier ?cid .
	?i mission:hasIdentifier ?iid .
}
ORDER BY ?c ?i
