PREFIX mission: <http://example.com/tutorial/vocabulary/mission#>

SELECT ?graph ?id ?x
WHERE {
    GRAPH ?graph {
        {
            SELECT ?id
            WHERE { GRAPH ?g { ?x mission:hasIdentifier ?id . } }
            GROUP BY ?id
            HAVING (COUNT(?x) > 1)
        }
        ?x mission:hasIdentifier ?id .
    }
}
ORDER BY ?graph ?id ?x
