PREFIX mission: <http://example.com/tutorial/vocabulary/mission#>

SELECT ?id ?x
WHERE {
    {
        SELECT ?id
        WHERE {
        ?x mission:hasIdentifier ?id .
        }
        GROUP BY ?id
        HAVING (COUNT(?x) > 1)
    }
    ?x mission:hasIdentifier ?id .
}
ORDER BY ?id ?x
