PREFIX pizza:       <http://example.com/tutorial1/vocabulary/pizza#>
PREFIX rdfs: 		<http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?pizza
WHERE {
    ?pizza a pizza:Pizza .
    FILTER NOT EXISTS {
       ?pizza pizza:hasTopping ?nvt . 
       FILTER NOT EXISTS { 
       	   ?nvt a pizza:VegetableTopping 
       }
    } 
}